# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Atlas Copco Anomaly Detection Dashboard
Build with: pyinstaller atlas_dashboard.spec
"""

import os

block_cipher = None

# All hidden imports needed by Streamlit + our app
hidden_imports = [
    # Streamlit core
    'streamlit',
    'streamlit.runtime',
    'streamlit.runtime.scriptrunner',
    'streamlit.runtime.scriptrunner.script_cache',
    'streamlit.elements',
    'streamlit.elements.lib',
    'streamlit.proto',
    'streamlit.server',
    'streamlit.components',
    'streamlit.components.v1',
    'streamlit.testing',
    'streamlit.cli',
    'streamlit.commands',
    'streamlit.delta_generator',
    'streamlit.errors',
    'streamlit.runtime.state',
    'streamlit.source_util',
    'streamlit.type_util',
    'streamlit.config',
    'streamlit.config_option',
    'streamlit.file_util',
    'streamlit.string_util',
    'streamlit.url_util',
    'streamlit.version',
    'streamlit.watcher',
    'streamlit.watcher.path_watcher',
    'streamlit.watcher.folder_black_list',
    # Streamlit components (runtime imports)
    'streamlit.components.v1.component_registry',
    'streamlit.components.v1.components_pb2',
    'streamlit.components.types',
    'streamlit.components.types.base_component_registry',
    'streamlit.elements.alert',
    'streamlit.elements.arrow',
    'streamlit.elements.balloons',
    'streamlit.elements.button',
    'streamlit.elements.checkbox',
    'streamlit.elements.color_picker',
    'streamlit.elements.dataframe_selector',
    'streamlit.elements.deck_gl_json_chart',
    'streamlit.elements.doc_string',
    'streamlit.elements.empty',
    'streamlit.elements.exception',
    'streamlit.elements.file_uploader',
    'streamlit.elements.graphviz_chart',
    'streamlit.elements.heading',
    'streamlit.elements.html',
    'streamlit.elements.iframe',
    'streamlit.elements.image',
    'streamlit.elements.json',
    'streamlit.elements.layouts',
    'streamlit.elements.lib.dialog',
    'streamlit.elements.lib.event_utils',
    'streamlit.elements.lib.file_uploader',
    'streamlit.elements.lib.image_utils',
    'streamlit.elements.lib.mutable_status',
    'streamlit.elements.lib.policy',
    'streamlit.elements.markdown',
    'streamlit.elements.metric',
    'streamlit.elements.multiselect',
    'streamlit.elements.number_input',
    'streamlit.elements.plotly_chart',
    'streamlit.elements.progress',
    'streamlit.elements.pyplot',
    'streamlit.elements.radio',
    'streamlit.elements.selectbox',
    'streamlit.elements.select_slider',
    'streamlit.elements.slider',
    'streamlit.elements.snow',
    'streamlit.elements.text',
    'streamlit.elements.text_widgets',
    'streamlit.elements.time_widgets',
    'streamlit.elements.toast',
    'streamlit.elements.vega_charts',
    'streamlit.elements.video',
    'streamlit.elements.write',
    # Plotly (for charts)
    'plotly',
    'plotly.graph_objects',
    'plotly.subplots',
    'plotly.graph_objs',
    'plotly.validators',
    'plotly.io',
    'plotly.io._renderers',
    'plotly.io._json',
    # Pandas
    'pandas',
    'pandas.core',
    'pandas.core.arrays',
    'pandas.core.arrays.sparse',
    'pandas.core.arrays.string_',
    'pandas.core.arrays.masked',
    'pandas.core.dtypes',
    'pandas.core.groupby',
    'pandas.core.indexes',
    'pandas.core.indexing',
    'pandas.core.internals',
    'pandas.core.reshape',
    'pandas.core.tools',
    'pandas.io',
    'pandas.io.formats',
    'pandas.io.formats.style',
    'pandas.io.parsers',
    'pandas.io.excel',
    'pandas.tseries',
    # NumPy
    'numpy',
    'numpy.core',
    'numpy.core.multiarray',
    'numpy.linalg',
    # Scikit-learn
    'sklearn',
    'sklearn.ensemble',
    'sklearn.ensemble._forest',
    'sklearn.ensemble._iforest',
    'sklearn.preprocessing',
    'sklearn.preprocessing._data',
    'sklearn.decomposition',
    'sklearn.decomposition._pca',
    'sklearn.tree',
    'sklearn.tree._tree',
    'sklearn.tree._splitter',
    'sklearn.utils',
    'sklearn.utils._cython_blas',
    'sklearn.neighbors',
    'sklearn.svm',
    'sklearn.linear_model',
    'sklearn.metrics',
    'sklearn.metrics.cluster',
    'sklearn.metrics.pairwise',
    # SciPy
    'scipy',
    'scipy.fft',
    'scipy.special',
    'scipy.special._ufuncs_cxx',
    'scipy.linalg',
    'scipy.linalg.cython_blas',
    'scipy.linalg.cython_lapack',
    'scipy.integrate',
    'scipy.optimize',
    'scipy.optimize._minimize',
    'scipy.optimize._lsq',
    'scipy.sparse',
    'scipy.sparse.csgraph',
    'scipy.spatial',
    'scipy.spatial.distance',
    'scipy.spatial.transform',
    'scipy.stats',
    'scipy.stats._stats',
    # Openpyxl (for Excel reading)
    'openpyxl',
    # Other
    'json',
    'hashlib',
    'glob',
    'pickle',
    'warnings',
]

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include the Streamlit app and related Python files
        ('app.py', '.'),
        ('anomaly_detector.py', '.'),
        ('model_manager.py', '.'),
        ('train_and_detect.py', '.'),
    ],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib.tests',
        'numpy.testing',
        'pytest',
        'IPython',
        'jupyter',
        'notebook',
        'docutils',
        'PySide6',
        'PySide2',
        'PyQt6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='AtlasDashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # Keep console for debugging
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign=None,
    entitlements_file=None,
    icon=None,  # Add icon path here if you have one
)
